version: 2

aliases:
  - &restore-cache
      keys:
        - dependency-cache-{{ checksum "package.json" }}-3

  - &save-cache
      key: dependency-cache-{{ checksum "package.json" }}-3
      paths:
        - node_modules

  - &restore-cache-components
      keys:
        - dependency-cache-{{ checksum "packages/components/package.json" }}-3

  - &save-cache-components
      key: dependency-cache-{{ checksum "packages/components/package.json" }}-3
      paths:
        - packages/components/node_modules

  - &restore-cache-components-stencil
      keys:
        - stencil-cache-2

  - &save-cache-components-stencil
      key: stencil-cache-2
      paths:
        - packages/components/.stencil
        - packages/components/screenshot/images

  - &restore-cache-icons
      keys:
        - dependency-cache-{{ checksum "packages/icons/package.json" }}-3

  - &save-cache-icons
      key: dependency-cache-{{ checksum "packages/icons/package.json" }}-3
      paths:
        - packages/icons/node_modules

  - &restore-cache-icons-stencil
      keys:
        - stencil-cache-2

  - &save-cache-icons-stencil
      key: stencil-cache-2
      paths:
        - packages/icons/.stencil
        - packages/icons/screenshot/images

  - &restore-cache-styles
      keys:
        - dependency-cache-{{ checksum "packages/styles/package.json" }}-3

  - &save-cache-styles
      key: dependency-cache-{{ checksum "packages/styles/package.json" }}-3
      paths:
        - packages/styles/node_modules

  - &restore-cache-design-tokens
      keys:
        - dependency-cache-{{ checksum "packages/design-tokens/package.json" }}-3

  - &save-cache-design-tokens
      key: dependency-cache-{{ checksum "packages/design-tokens/package.json" }}-3
      paths:
        - packages/design-tokens/node_modules

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
  working_directory: /tmp/workspace

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - save_cache: *save-cache
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-components:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-components
      - restore_cache: *restore-cache-components-stencil
      - run:
          command: npm install
          working_directory: /tmp/workspace/packages/components
      - save_cache: *save-cache-components
      - run:
          command: npm run build -- --ci
          working_directory: /tmp/workspace/packages/components
      - save_cache: *save-cache-components-stencil
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-styles:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-styles
      - run:
          command: npm install
          working_directory: /tmp/workspace/packages/styles
      - save_cache: *save-cache-styles
      - run:
          command: npm run build -- --ci
          working_directory: /tmp/workspace/packages/styles
      - save_cache: *save-cache-styles
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-tokens:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-design-tokens
      - run:
          command: npm install
          working_directory: /tmp/workspace/packages/design-token
      - save_cache: *save-cache-design-tokens
      - run:
          command: npm run build -- --ci
          working_directory: /tmp/workspace/packages/design-token
      - save_cache: *save-cache-design-tokens
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-icons:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-icons
      - restore_cache: *restore-cache-icons-stencil
      - run:
          command: npm install
          working_directory: /tmp/workspace/packages/icons
      - save_cache: *save-cache-icons
      - run:
          command: npm run build -- --ci
          working_directory: /tmp/workspace/packages/icons
      - save_cache: *save-cache-icons-stencil
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
  
  test-styles-clean-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checking clean build
          command: git diff --exit-code
          working_directory: /tmp/workspace/packages/styles

  test-components-clean-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checking clean build
          command: git diff --exit-code
          working_directory: /tmp/workspace/packages/components

  test-design-tokens-clean-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checking clean build
          command: git diff --exit-code
          working_directory: /tmp/workspace/packages/design-tokens

  test-icons-clean-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checking clean build
          command: git diff --exit-code
          working_directory: /tmp/workspace/packages/icons

  test-styles-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint.sass
          working_directory: /tmp/workspace/packages/styles

  test-components-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/packages/components

  test-components-spec:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run test --ci
          working_directory: /tmp/workspace/packages/components
  
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lerna publish
          working_directory: /tmp/workspace

workflows:
  version: 2
  build:
    jobs:
      - build
      - build-components:
          requires: [build]
      - build-styles:
          requires: [build]
      - build-icons:
          requires: [build]
      - build-design-tokens:
          requires: [build]
      - test-components-clean-build:
          requires: [build-components]
      - test-styles-clean-build:
          requires: [build-styles]
      - test-icons-clean-build:
          requires: [build-icons]
      - test-design-tokens-clean-build:
          requires: [build-design-tokens]
      - test-components-lint:
          requires: [test-components-clean-build]
      - test-styles-lint:
          requires: [build-styles]
      - test-components-spec:
          requires: [test-components-clean-build]
      # - publish:
      #     requires:
      #       - build-components
      #       - build-styles
      #       - test-styles-clean-build
      #       - test-components-clean-build
      #       - test-components-lint
      #       - test-styles-lint
      #       - test-components-spec
      #     filters:
      #       branches:
      #         only: master
