version: 2

aliases:
  - &restore-cache
      keys:
        - dependency-cache-{{ checksum "package.json" }}-3

  - &save-cache
      key: dependency-cache-{{ checksum "package.json" }}-3
      paths:
        - node_modules

  - &restore-cache-components
      keys:
        - dependency-cache-{{ checksum "packages/components/package.json" }}-3

  - &save-cache-components
      key: dependency-cache-{{ checksum "packages/components/package.json" }}-3
      paths:
        - packages/components/node_modules

  - &restore-cache-components-stencil
      keys:
        - stencil-cache-2

  - &save-cache-components-stencil
      key: stencil-cache-2
      paths:
        - packages/components/.stencil
        - packages/components/screenshot/images

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
  working_directory: /tmp/workspace

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - run: npm run setup
      - save_cache: *save-cache
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-components:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-components
      - restore_cache: *restore-cache-components-stencil
      - run:
          command: npm install
          working_directory: /tmp/workspace/components
      - save_cache: *save-cache-components
      - run:
          command: npm run build -- --ci
          working_directory: /tmp/workspace/components
      - save_cache: *save-cache-components-stencil
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  test-components-clean-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checking clean build
          command: git diff --exit-code
          working_directory: /tmp/workspace/components

  test-components-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/components

  test-components-spec:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run test.spec --ci
          working_directory: /tmp/workspace/components

workflows:
  version: 2
  build:
    jobs:
      - build
      - build-components:
          requires: [build]
      - test-components-clean-build:
          requires: [build-components]
      - test-components-lint:
          requires: [build-components]
      - test-components-spec:
          requires: [build-components]
